[package]
name = "pv_porcupine_filedemo"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
rodio = "0.14"
itertools = "0.10.1"
pv_porcupine = { path = "../../../binding/rust" }
chrono = "0.4.19"
