name: porcupine_flutter
description: A Flutter plugin for Picovoice's Porcupine offline wake word engine.
version: 3.0.5
homepage: https://picovoice.ai/
repository: https://github.com/Picovoice/porcupine/
documentation: https://picovoice.ai/docs/porcupine/

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  path_provider: ^2.0.9
  flutter:
    sdk: flutter

  flutter_voice_processor: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.porcupine
        pluginClass: PorcupinePlugin
      ios:
        pluginClass: PorcupinePlugin
