name: porcupine_flutter
description: A Flutter plugin for Picovoice's Porcupine offline wake word engine.
version: 2.0.4
homepage: https://picovoice.ai/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  path_provider: ^2.0.1
  flutter:
    sdk: flutter

  flutter_voice_processor: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.porcupine
        pluginClass: PorcupinePlugin
      ios:
        pluginClass: PorcupinePlugin
