name: porcupine_demo
description: Demonstrates how to use the porcupine plugin.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_picker: ^2.7.0
  porcupine_flutter:
    path: ../../binding/flutter
  path: ^1.8.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/keywords/android/
    - assets/keywords/ios/
    - assets/test_resources/
    - assets/test_resources/audio_samples/
    - assets/test_resources/keyword_files/
    - assets/test_resources/model_files/
