name: .NET Demos

on:
  workflow_dispatch:
  push:
    branches: [ master, v2.0 ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'
  pull_request:
    branches: [ master, v2.0 ]
    paths:
      - 'demo/dotnet/**'
      - '!demo/dotnet/README.md'

defaults:
  run:
    working-directory: demo/dotnet/PorcupineDemo

jobs:
  build-micdemo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Pack binding for local ref
      run: dotnet pack -c Release
      working-directory: binding/dotnet
    
    - name: Package restore
      run: dotnet restore

    - name: Dotnet build micdemo
      run: dotnet build -c MicDemo.Release

  build-filedemo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Pack binding for local ref
      run: dotnet pack -c Release
      working-directory: binding/dotnet
    
    - name: Package restore
      run: dotnet restore

    - name: Dotnet build filedemo
      run: dotnet build -c FileDemo.Release
