name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/common/**'
      - 'lib/java/**'
      - 'resources/keyword_files/beaglebone/**'
      - 'resources/keyword_files/jetson/**'
      - 'resources/keyword_files/linux/**'
      - 'resources/keyword_files/mac/**'
      - 'resources/keyword_files/raspberry-pi/**'
      - 'resources/keyword_files/windows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/common/**'
      - 'lib/java/**'
      - 'resources/keyword_files/beaglebone/**'      
      - 'resources/keyword_files/jetson/**'
      - 'resources/keyword_files/linux/**'
      - 'resources/keyword_files/mac/**'
      - 'resources/keyword_files/raspberry-pi/**'
      - 'resources/keyword_files/windows/**'

defaults:
  run:
    working-directory: binding/java

jobs:
  # build-github-hosted:
    # runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]

    # steps:
    # - uses: actions/checkout@v2

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    #     distribution: 'adopt'

    # - name: Validate Gradle wrapper
    #   uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    # - name: Build
    #   run: ./gradlew assemble

    # - name: Test
    #   run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [jetson]

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: echo "machine is $RUNNER_NAME ok"

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"