name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/common/**'
      - 'lib/java/**'
      - 'resources/keyword_files/beaglebone/**'
      - 'resources/keyword_files/jetson/**'
      - 'resources/keyword_files/linux/**'
      - 'resources/keyword_files/mac/**'
      - 'resources/keyword_files/raspberry-pi/**'
      - 'resources/keyword_files/windows/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/common/**'
      - 'lib/java/**'
      - 'resources/keyword_files/beaglebone/**'      
      - 'resources/keyword_files/jetson/**'
      - 'resources/keyword_files/linux/**'
      - 'resources/keyword_files/mac/**'
      - 'resources/keyword_files/raspberry-pi/**'
      - 'resources/keyword_files/windows/**'
      - '.github/workflows/java.yml'

defaults:
  run:
    working-directory: binding/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}


    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          performance_threshold_sec: 0.3
        - os: windows-latest
          performance_threshold_sec: 0.35
        - os: macos-latest
          performance_threshold_sec: 0.35

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" -DperformanceThresholdSec="${{matrix.performance_threshold_sec}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
        - machine: rpi2
          performance_threshold_sec: 5.5
        - machine: rpi3-32
          performance_threshold_sec: 2.0
        - machine: rpi3-64
          performance_threshold_sec: 2.5
        - machine: rpi4-32
          performance_threshold_sec: 1.5
        - machine: rpi4-64
          performance_threshold_sec: 1.5
        - machine: jetson
          performance_threshold_sec: 2.0
        - machine: beaglebone
          performance_threshold_sec: 12.0

    steps:
    - uses: actions/checkout@v2

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" -DperformanceThresholdSec="${{matrix.performance_threshold_sec}}"
